---
galaxy_info:
  role_name: desktop
  author: Daniel Peyer
  description: FreeBSD Sway or DWM desktop configuration.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: FreeBSD
      versions:
        - all

dependencies: []
