---
- name: Install DWM X session
  ansible.builtin.template:
    src: xinitrc.j2
    dest: "{{ workstation_home }}/.xinitrc"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0755"

- name: Install Picom configuration
  ansible.builtin.template:
    src: picom.conf.j2
    dest: "{{ workstation_home }}/.config/picom/picom.conf"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0644"

- name: Install Dunst configuration
  ansible.builtin.template:
    src: dunstrc.j2
    dest: "{{ workstation_home }}/.config/dunst/dunstrc"
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0644"
