---
- name: Configure x session for dwm
  ansible.builtin.include_tasks: "dwm_xsession.yml"

- name: Configure picom
  ansible.builtin.include_tasks: "dwm_picom.yml"

- name: Configure dunst
  ansible.builtin.include_tasks: "dwm_dunst.yml"  

