---
- name: Load selected desktop variables
  ansible.builtin.include_vars:
    file: "{{ desktop_environment }}.yml"

- name: Manage custom dwm installation directory
  block:
    - name: Ensure the ~/src directory exists
      ansible.builtin.file:
        path: "{{ workstation_home }}/src"
        state: directory
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
        mode: '0755'
      become: yes

    - name: Clone dwm-flexipatch repository as root
      ansible.builtin.git:
        repo: 'git@github.com:lirux9873/dwm-flexipatch.git'
        dest: "{{ workstation_home }}/src/dwm-flexipatch"
        version: master
        accept_hostkey: yes
        key_file: "{{ workstation_home }}/.ssh/id_ed25519"  # Path to your private key
        clone: yes
        update: yes
      become: yes

    - name: Ensure correct user ownership on cloned repo files
      ansible.builtin.file:
        path: "{{ workstation_home }}/src/dwm-flexipatch"
        state: directory
        recurse: yes
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
      become: yes

  when: desktop_environment == 'dwm'


- name: Install desktop packages
  ansible.builtin.package:
    name: "{{ desktop_packages }}"
    state: present

- name: Create desktop configuration directories
  ansible.builtin.file:
    path: "{{ workstation_home }}/{{ item }}"
    state: directory
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0755"
  loop: "{{ desktop_config_directories }}"

- name: Configure selected desktop
  ansible.builtin.include_tasks: "{{ desktop_environment }}.yml"
