---
- name: Load selected desktop variables
  ansible.builtin.include_vars:
    file: "{{ desktop_environment }}.yml"

- name: System-wide installation of custom dwm
  block:
    - name: Ensure the system source directory exists
      ansible.builtin.file:
        path: "/usr/local/src"
        state: directory
        owner: root
        group: wheel
        mode: '0755'

    - name: Clone private dwm-flexipatch repository to system source
      ansible.builtin.git:
        repo: 'git@github.com:lirux9873/dwm-flexipatch.git'
        dest: "/usr/local/src/dwm-flexipatch"
        version: master
        accept_hostkey: yes
        # TODO: Use a dedicated key for this repository instead of borrowing the user's key
        key_file: "{{ workstation_home }}/.ssh/id_ed25519"  # Borrowing the key to authenticate
        clone: yes
        update: yes

    - name: Clean and build dwm using gmake
      community.general.make:
        chdir: "/usr/local/src/dwm-flexipatch"
        target: dist
        make: gmake

    - name: Install dwm using gmake
      community.general.make:
        chdir: "/usr/local/src/dwm-flexipatch"
        target: install
        make: gmake

  when: desktop_environment == 'dwm'

- name: Install st
  ansible.builtin.include_tasks: "st.yml"
  when: desktop_environment == 'dwm'

- name: Install desktop packages
  ansible.builtin.package:
    name: "{{ desktop_packages }}"
    state: present

- name: Create desktop configuration directories
  ansible.builtin.file:
    path: "{{ workstation_home }}/{{ item }}"
    state: directory
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0755"
  loop: "{{ desktop_config_directories }}"

- name: Configure selected desktop
  ansible.builtin.include_tasks: "{{ desktop_environment }}.yml"
