---
- name: Clone private st-flexipatch repository to system source
  ansible.builtin.git:
    repo: 'git@github.com:lirux9873/st-flexipatch.git'
    dest: "/usr/local/src/st-flexipatch"
    version: master
    accept_hostkey: yes
    # TODO: Use a dedicated key for this repository instead of borrowing the user's key
    key_file: "{{ workstation_home }}/.ssh/id_ed25519"  # Borrowing the key to authenticate
    clone: yes
    update: yes

- name: Clean and build st using gmake
  community.general.make:
    chdir: "/usr/local/src/st-flexipatch"
    target: dist
    make: gmake

- name: Install st using gmake
  community.general.make:
    chdir: "/usr/local/src/st-flexipatch"
    target: install
    make: gmake