---
galaxy_info:
  role_name: ansible_pull
  author: Daniel Peyer
  description: Scheduled local configuration through ansible-pull and cron.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: FreeBSD
      versions:
        - all

dependencies: []
