---
- name: Create standard user directories
  ansible.builtin.command:
    argv:
      - /usr/local/bin/xdg-user-dirs-update
  become: true
  become_user: "{{ workstation_user }}"
  environment:
    HOME: "{{ workstation_home }}"
  register: xdg_user_dirs
  changed_when: false
  when: workstation_create_xdg_directories | bool

- name: Create local user binary directory
  ansible.builtin.file:
    path: "{{ workstation_home }}/.local/bin"
    state: directory
    owner: "{{ workstation_user }}"
    group: "{{ workstation_user }}"
    mode: "0755"
