---
galaxy_info:
  role_name: workstation
  author: Daniel Peyer
  description: Common FreeBSD graphical workstation packages and services.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: FreeBSD
      versions:
        - all

dependencies: []
